### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by cslee99** [jahongir7174/DeepLabV3#1]
I used DeepLabv3 to instance segmentation. Each train folder has a CT image, and train_labels folder contains an instance mask file so that urinary stones can be segmented. Since only urinary stone is segmented, the content of class_dict.csv is also modified as follows.
Can I use DeepLabv3 in instance Segmentation?
----- class_dict.csv -----
name r g b
Stone 64 128 64

**question 1.** 
When training, try with the file below.
-train, train_labels
When testing, try with the following file.
-test, test_labels

yolov5 predicted without labeling when testing. But why does deeplabv3 need the test_labels folder for testing? Shouldn't it be predicted even without the test_labels folder?

**question 2.** 
Loss on train is expressed in nan.
There is no change in the loss, so the weight file is always saved in the same size.
So the predict doesn't work.
----- train log -----
6-0.000000
7-0.000000
.....
129-nan
130-nan
----- saved weight -----
model1.h5 : 52,918KB
.....
model50.h5 : 52.918KB

**Comment by jahongir7174** [comment]
Sorry for the late response,
DeepLAbV3+ is for semantic segmentation task not for instance segmentation
1. test label path is just for plotting the difference between prediction and gt
2. I updated the repo, you can use this version, I hope it is stable now
For further dataset structure, you can refer CamVid dataset
