### ISSUE TITLE
#About model parameters

### ISSUE THREAD

**Issue by tanveer6715** [jahongir7174/DeepLabV3#4]
Hi,
Thanks for you code. I just find the model parameters which is around 6 million. But most of the researchers report around 78 million parameters of DeepLab v3+. Will you guide me about this problem.
Thanks.

**Comment by jahongir7174** [comment]
hello,
original deeplabv3+ uses xception as a backbone, efficientnetv2-s is used as a backbone in this repo

**Comment by tanveer6715** [comment]
Thank you for your response. In efficient netv2 paper the authors report 24 M parameters. As you use efficient netv2 in this repo then why its still show around 6 M parameters?

**Comment by jahongir7174** [comment]
Structure of DeepLabV3+
![image](https://user-images.githubusercontent.com/71679734/134619810-c3d130a7-6726-4011-882e-f4295cd55113.png)


Structure of EfficnentNetV2-S
![image](https://user-images.githubusercontent.com/71679734/134619903-fe6115f5-a2f2-4ff2-8f63-e3a17d914839.png)


I hope these figures answer your question

**Comment by tanveer6715** [comment]
Thank you
